== Demonstrations

This page lists all of the demonstrations that are to be presented during the Demonstration session. 

Participants (including any member of the audience) will be invited to present a demonstration of their prototype during the Demonstrations session. 

All participants will be able to vote for their favorite demonstration

*Anyone planning to do a demo should register their demo by 17:30 EDT (21:30 GMT) on this page.*

Simply create a Pull Request and we will merge it into the document.

=== Entry 1

Title: *CubeWerx TEP Demonstration*

Presenter: *Panagiotis (Peter) A. Vretanos - [CubeWerx Inc.]*

Abstract: A demonstration of part of a themathic exploitation platform that shows OGC API - Processes and OGC API - Records working together to execute deployed processes in distributed cloud environment (AWS).

=== Entry 2

Title: *CubeWerx OGC API - Records with legacy output formats*

Presenter: *Panagiotis (Peter) A. Vretanos - [CubeWerx Inc.]*

Abstract: A quick demo of an OGC API - Records server generating legacy output formats (CSW Record, etc.).

=== Entry 3

Title: *Title of the demonstration*

Presenter: *FirstName LastName - [OrganizationName optional]*

Abstract: *Maximum 100 word description*


=== Entry 4

Title: *Title of the demonstration*

Presenter: *FirstName LastName - [OrganizationName optional]*

Abstract: *Maximum 100 word description*


=== Entry 5

Title: *Title of the demonstration*

Presenter: *FirstName LastName - [OrganizationName optional]*

Abstract: *Maximum 100 word description*


=== Entry 6

Title: *Title of the demonstration*

Presenter: *FirstName LastName - [OrganizationName optional]*

Abstract: *Maximum 100 word description*


