== Demonstrations

This page lists all of the demonstrations that are to be presented during the Demonstration session. 

Participants (including any member of the audience) will be invited to present a demonstration of their prototype during the Demonstrations session. 

All participants will be able to vote for their favorite demonstration

=== Entry 1

Title: *Title of the demonstration*

Presenter: *FirstName LastName - [OrganizationName optional]*

Abstract: *Maximum 100 word description*

=== Entry 2

Title: *Title of the demonstration*

Presenter: *FirstName LastName - [OrganizationName optional]*

Abstract: *Maximum 100 word description*


=== Entry 3

Title: *Title of the demonstration*

Presenter: *FirstName LastName - [OrganizationName optional]*

Abstract: *Maximum 100 word description*


=== Entry 4

Title: *Title of the demonstration*

Presenter: *FirstName LastName - [OrganizationName optional]*

Abstract: *Maximum 100 word description*


=== Entry 5

Title: *Title of the demonstration*

Presenter: *FirstName LastName - [OrganizationName optional]*

Abstract: *Maximum 100 word description*


=== Entry 6

Title: *Title of the demonstration*

Presenter: *FirstName LastName - [OrganizationName optional]*

Abstract: *Maximum 100 word description*


