== Title of the Session: Getting Acquainted with GeoPose

The session will take place on June 16th, 2021 at 14:45 - 16:15 EDT.

Abstract: GeoPose is a draft OGC standard for encoding the location and orientation of objects in the real world. During this session, developers with limited geospatial engineering experience will learn how to:

1.  explore the underlying concepts of GeoPose and experiment with them in different scenarios using the GeoPose Sandbox,
2.  work with the eight different JSON encodings of GeoPose with an example GeoPose service giving the GeoPose of the sun for any time or location and
3.  use the draft OSCP GeoPose-compliant protocol to retrieve content from a Spatial Content Record.

Although there can be preparations in advance, such as mapping an area with a Visual Positioning Service, developers will not need any content or to install any proprietary software to experience the benefits of GeoPose and the modules of this session.



=== More details

There will be three modules, each with a different objective and outcome.

* Module 1: Using the GeoPose Sandbox, a development playground, the participants will be able to explore the underlying concepts of GeoPose and experiment with them in different scenarios. For example, the developer will learn how to transform location and orientation from one representation to another. 

* Module 2: The developer will learn about and work with the eight different JSON encodings of GeoPose with an example web service that gives GeoPose of the sun for any time or location.

* Module 3: The developer will learn how to use the OARC's Open Spatial Computing Platform "GeoPose Protocol" to based on visual positioning. Using the OSCP GeoPose-compliant protocol, the developer will post an image to a protocol compliant server and receive a GeoPose pose response back. 
** Prerequisites for running the code:
*** Command line window
*** GIT
*** Text editor or IDE
*** Python 3 installed
*** PIP 

*Module Leaders*

* Module 1: Mikel Salazar, Augmented Interaction/Open AR Cloud association
* Module 2: Steve Smyth, Open Site Plan
* Module 3: James Jackson and Jan-Erik Vinje, Open AR Cloud association
